#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/hypr"
RASI="$DIR/rofi/runner.rasi"

export ELECTRON_OZONE_PLATFORM_HINT=wayland
# Run
rofi \
    -show run \
	-theme ${RASI}
